---
- hosts: web
  sudo: yes

  vars:
    webpackages:
    - build-essential
    - libtool
    - pkg-config 
    - build-essential
    - autoconf
    - automake
    - uuid-dev
    - python-dev
    #erlangpackages:


    zmq_version: 4.0.5
    
    zmq_install_cmd:
    - ./configure
    - make
    - make install
    - ldconfig



  tasks:
    ## =========================================
    # =========== Install basic packages from apt

    - action: shell whoami
      register: whoami

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: upgrade the distro
      apt: upgrade=yes

    - name: install packages
      apt: pkg={{ item }} state=present
      with_items: webpackages
      
    ## =========================================
    # ============= Install zeromq from source

    - name: check if zmq is installed
      stat: path=/usr/local/lib/libzmq.so.4
      register: zmq_installed
      ignore_errors: True
     
    - include: tasks/zeromq.yml
      when: not zmq_installed.stat.exists
      

    - name: check if pip is installed
      stat: path=/usr/local/bin/pip
      register: pip_installed

    - include: tasks/pip.yml
      when: not pip_installed.stat.exists

    #- name: install Cython
    #  pip: name=Cython
    #  when: not pip_installed.stat.exists
    
    - name: install rupert requirements
      pip: requirements=/home/vagrant/working/rupert/requirements.txt
  